"""empty message

Revision ID: 0bad09eca9b4
Revises: da0e365b163c
Create Date: 2022-08-01 13:19:58.441434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bad09eca9b4'
down_revision = 'da0e365b163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # use this if you don't use SQLite
    # op.drop_column('post', 'slug')
    
    # if SQLite is used
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('slug')
    # ### end Alembic commands ###
