"""empty message

Revision ID: 729fc3a23c8f
Revises: 
Create Date: 2023-03-31 20:22:24.132368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729fc3a23c8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_model')
    # ### end Alembic commands ###
